name: Release a new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (SemVer)'
        required: true 
        type: string
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ github.event.inputs.version }}',
              sha: context.sha
            })